databases:
  - name: adote
    databaseName: adote_ouah
    user: adote_ouah_user

services:
  - type: web
    name: adote
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn adote.wsgi:application"
    envVars:
      - key: postgresql://adote_ouah_user:EUnPfrJTnvdYYj3v17xgEZQlWyRt9fDhW@dpg-ct6uvql6l47c738cqfug-a.oregon-postgres.render.com/adote_ouah 1 
        fromDatabase:
          name: adote_ouah
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4