# Generated by Django 4.1.5 on 2023-01-29 18:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0004_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto'),
        ),
    ]
