# Generated by Django 4.1.5 on 2023-02-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0005_alter_pet_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
    ]
