# Generated by Django 4.1.5 on 2023-02-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0007_pet_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porte', models.CharField(max_length=20)),
            ],
        ),
    ]
