# Generated by Django 4.1.5 on 2023-02-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0008_porte'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='porte',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='divulgar.porte'),
            preserve_default=False,
        ),
    ]
