# Generated by Django 4.1.5 on 2023-02-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0011_pet_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='raca',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='divulgar.animal'),
            preserve_default=False,
        ),
    ]
